#!/usr/bin/env python
"""
Test script to demonstrate matrix format displays from f1_performance_analysis.py
"""

# Sample matrix output demonstration
print("\n" + "="*150)
print("MATRIX FORMAT DEMONSTRATION - F1 Performance Analysis")
print("="*150)

# 1. Overtakes Matrix (Year-by-Year Performance)
print("\n1. OVERTAKES MATRIX FORMAT")
print("="*150)
print("Year-by-Year Performance Matrix:")
print("="*150)
print("Driver                                   2020                2021                2022                2023                2024")
print("                             Start→Fin    +/-    Start→Fin    +/-    Start→Fin    +/-    Start→Fin    +/-    Start→Fin    +/-")
print("-"*125)
print("George Russell               12→18       -6.0      17→8        +9.0       1→3        -2.0      18→6       +12.0      17→8        +9.0  ")
print("Sergio Pérez                  4→7        -3.0       4→nan      +nan      11→5        +6.0       9→3        +6.0      16→7        +9.0  ")
print("Charles Leclerc               6→11       -5.0       7→nan      +nan       3→6        -3.0       6→7        -1.0       6→4        +2.0  ")
print("Lewis Hamilton                1→1        +0.0       1→2        -1.0       7→2        +5.0       1→4        -3.0       5→3        +2.0  ")
print("\nFormat: Start→Finish  +/- (position change)")
print("Note: 'nan' indicates DNF (Did Not Finish)")

# 2. Points Matrix
print("\n\n2. POINTS MATRIX FORMAT")
print("="*120)
print("Year-by-Year Points Matrix:")
print("="*120)
print("Driver                                   2020                2021                2022                2023                2024")
print("                               Pts  Avg  Best      Pts  Avg  Best      Pts  Avg  Best      Pts  Avg  Best      Pts  Avg  Best")
print("-"*120)
print("Oscar Piastri                     —                   —                   —            10  10.0     5       25  25.0     1     ")
print("Lando Norris                0   nan    13        0   nan   nan        6   6.0     7       18  18.0     2       18  18.0     2     ")
print("Lewis Hamilton             26  26.0     1       18  18.0     2       19  19.0     2       12  12.0     4       15  15.0     3     ")
print("Max Verstappen             18  18.0     2        2   2.0     9       25  25.0     1       26  26.0     1       10  10.0     5     ")
print("\nFormat: Points  Average  Best-Finish")
print("Note: '—' indicates driver didn't race that year")

# 3. Teammate Battles Matrix
print("\n\n3. TEAMMATE BATTLES MATRIX FORMAT")
print("="*120)
print("Year-by-Year Teammate Battles:")
print("="*120)
print("Driver                                   2020                2021                2022                2023                2024")
print("                                W-L (OT) [PP]       W-L (OT) [PP]       W-L (OT) [PP]       W-L (OT) [PP]       W-L (OT) [PP]")
print("-"*120)
print("Lewis Hamilton                1-0 (+0) [+0.0]         —               1-0 (+1) [+1.5]     1-0 (+0) [+0.0]     1-0 (+0) [+0.0]")
print("Fernando Alonso                   —               0-1 (+0) [+0.0]     1-0 (+1) [+1.5]     1-0 (+0) [+0.0]     0-1 (-1) [-1.5]")
print("Max Verstappen                1-0 (+0) [+0.0]         —               1-0 (+0) [+0.0]     1-0 (+0) [+0.0]     1-0 (+0) [+0.0]")
print("Daniel Ricciardo              1-0 (+0) [+0.0]         —               0-1 (+0) [+0.0]     1-0 (+0) [+0.0]     0-1 (-1) [-1.5]")
print("\nFormat: Wins-Losses (Net Overtakes) [PrizePicks Points]")
print("Note: +1.5 points for overtaking teammate, -1.5 for being overtaken")

# 4. Starting Position Matrix
print("\n\n4. STARTING POSITION MATRIX FORMAT")
print("="*140)
print("Year-by-Year Starting Position Matrix:")
print("="*140)
print("Driver                                     2020                  2021                  2022                  2023                  2024")
print("                                Start  Pts/Race       Start  Pts/Race       Start  Pts/Race       Start  Pts/Race       Start  Pts/Race")
print("-"*140)
print("Lando Norris                 8.0          nan        6.0          nan        4.0          6.0        3.0         18.0        1.0         18.0    ")
print("Oscar Piastri                      —                     —                     —               4.0         10.0        2.0         25.0    ")
print("Max Verstappen               7.0         18.0        3.0          2.0       10.0         25.0        2.0         26.0        3.0         10.0    ")
print("Lewis Hamilton               1.0         26.0        1.0         18.0        7.0         19.0        1.0         12.0        5.0         15.0    ")
print("\nFormat: Starting-Position  Points/Race")

# Matrix formatting characteristics
print("\n\n" + "="*80)
print("MATRIX FORMATTING CHARACTERISTICS:")
print("="*80)
print("✓ Fixed-width columns for proper alignment")
print("✓ Clear year headers (showing last 5 years)")
print("✓ Consistent spacing between data points")
print("✓ Special characters properly displayed (→, —, +/-)")
print("✓ Format explanations included below each matrix")
print("✓ Handles missing data gracefully (nan, —)")
print("✓ Column headers clearly indicate data types")
print("✓ Visual separators (=, -) for readability")
print("✓ Proper numerical formatting (decimals, signs)")
print("✓ Legend/format key for each matrix type")

print("\n" + "="*80)
print("END OF MATRIX FORMAT DEMONSTRATION")
print("="*80)