name: Scrape DHL F1 Pit Stop Data

on:
  schedule:
    # Run every Thursday at 6 AM UTC
    - cron: '0 6 * * 4'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run DHL pit stop scraper
      run: |
        python dhl_current_season_scraper.py
      env:
        DISPLAY: ':99'
    
    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code data/dhl/ || echo "changes_detected=true" >> $GITHUB_OUTPUT
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes_detected == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/dhl/*.csv
        git commit -m "Update DHL pit stop data - $(date +'%Y-%m-%d')"
        git push